/* Project Euler Program 12
 * 
 * The sequence of triangle numbers is generated by adding the natural 
 * numbers. So the 7th triangle number would be 
 * 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 *   1: 1
 *   3: 1,3
 *   6: 1,2,3,6
 *  10: 1,2,5,10
 *  15: 1,3,5,15
 *  21: 1,3,7,21
 *  28: 1,2,4,7,14,28
 * 
 * We can see that 28 is the first triangle number to have over five 
 * divisors.  What is the value of the first triangle number to have 
 * over five hundred divisors?
 * 
 * Answer = 76576500
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "primes/primes.h"
#include "triangle/triangle.h"

#define DIVISORS 500

void printError(char* name);
void printHelp();

int main(int argc, char ** argv)
{
	size_t number = DIVISORS;

	if (argc == 2)
	{
		if (strcmp("-h", argv[1]) == 0 )
			printHelp();
		else
		{
			int32_t temp = atoi(argv[1]);
			if (temp < 0)
				printError(argv[0]);
			else
				number = (size_t)temp;
		}
	}

	size_t numDivisors = 0;
	size_t triangle;
	do
	{
		triangle = nextTriangle();
		
		//debug
		//printf("Testing triangle number %zu\n", triangle);
		
		numDivisors = divisorCount(triangle);
		
		//debug
		//printf("Divisors = %zu\n", numDivisors);
	} while (numDivisors <= number);
	
	printf("\nThe first triangle number with more than %zu divisors is %zu.\n\n", number, triangle);

	return EXIT_SUCCESS;
}


void printError(char* name)
{
	fprintf (stderr,"Usage: %s \n", name);
	fprintf (stderr,"Usage: %s -h \n", name);
	fprintf (stderr,"Usage: %s <number>\n", name);
	fprintf (stderr,"<number> must be a positive, whole number.\n");
	exit (EXIT_FAILURE);
}


void printHelp()
{
	printf("\nProject Euler Program 12\n\n"
		"28 is the first triangle number to have over five divisors (1, 2, 4, 7, 14, 28).  What is the "
		"value\nof the first triangle number to have over five hundred divisors?\n\n"
		"You can run the program without arguments to solve this problem as stated.  You can optionally\n"
		"provide a different number of divisors.\n\n");

	exit (EXIT_SUCCESS);
}

